export type TechIcon = { icon?: string; src?: string; invertable?: boolean };

export const TECH_ICONS: Record<string, TechIcon> = {
  'Next.js': { icon: 'nextjs/nextjs-original.svg', invertable: true },
  'React': { icon: 'react/react-original.svg' },
  'TypeScript': { icon: 'typescript/typescript-original.svg' },
  'JavaScript': { icon: 'javascript/javascript-original.svg' },
  'Tailwind': { icon: 'tailwindcss/tailwindcss-original.svg' },
  'Bootstrap': { icon: 'bootstrap/bootstrap-original.svg' },
  'HTML5': { icon: 'html5/html5-original.svg' },
  'CSS3': { icon: 'css3/css3-original.svg' },
  'Vite': { icon: 'vitejs/vitejs-original.svg' },
  'Socket.io': { icon: 'socketio/socketio-original.svg', invertable: true },
  'Node.js': { icon: 'nodejs/nodejs-original.svg' },
  'NestJS': { icon: 'nestjs/nestjs-original.svg' },
  'Express': { icon: 'express/express-original.svg', invertable: true },
  'Java': { icon: 'java/java-original.svg' },
  'MySQL': { icon: 'mysql/mysql-original.svg' },
  'MongoDB': { icon: 'mongodb/mongodb-original.svg' },
  'PostgreSQL': { icon: 'postgresql/postgresql-original.svg' },
  'Oracle DB': { icon: 'oracle/oracle-original.svg' },
  'Redis': { icon: 'redis/redis-original.svg' },
  'Docker': { icon: 'docker/docker-original.svg' },
  'Nginx': { icon: 'nginx/nginx-original.svg' },
  'VPS Ubuntu': { icon: 'ubuntu/ubuntu-original.svg' },
  'Ubuntu': { icon: 'ubuntu/ubuntu-original.svg' },
  'Linux': { icon: 'linux/linux-original.svg' },
  'Bash': { icon: 'bash/bash-original.svg', invertable: true },
  'Git': { icon: 'git/git-original.svg' },
  'GitHub': { icon: 'github/github-original.svg', invertable: true },
  'Sanity': { icon: 'sanity/sanity-original.svg' },
  'Swagger': { icon: 'swagger/swagger-original.svg' },
  'Framer Motion': { icon: 'framermotion/framermotion-original.svg' },
};
